### ISSUE TITLE
Bug: error in install by https://ui.shadcn.com/r/colors/

### ISSUE THREAD

**Issue by leomerida15** [vantezzen/autoform#104]
bunx shadcn@latest add  https://raw.githubuse
rcontent.com/vantezzen/auto-form/main/registry/auto-form.json
✔ Checking registry.
✔ Updating tailwind.config.ts
✔ Installing dependencies.
⠙ Updating files.

Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

The component at https://ui.shadcn.com/r/colors/blue.json was not found.
It may not exist at the registry. Please make sure it is a valid component.

OS: linux ubuntu
package manage: bun.js v1.1.28
![Uploading Screenshot from 2024-10-04 18-55-36.png…]()

**Comment by vantezzen** [comment]
Does installing other components with the CLI work? Looks like the shadcn config contains an invalid color scheme

**Comment by leomerida15** [comment]
This was an error associated with shadcn because in the components.json file the parameter tailwind.baseColor only allows a very limited list of colors
