### ISSUE TITLE
Update setError example. Deprecated?

### ISSUE THREAD

**Issue by tecoad** [vantezzen/autoform#108]
Hi @vantezzen,

I have tried to use the example from the readme:

```
<AutoForm
  onSubmit={(data, { setError }) => {
    // Do something with the data
    // Data is validated and coerced with zod automatically
    // You can use setError to set errors for the fields
  }}
/>
```

However i get an type error: 
Parameter 'data' implicitly has an 'any' type.ts(7006)
Binding element 'setError' implicitly has an 'any' type.ts(7031)

Seems this example is deprecated. Can you provide a short example on how to throw on error from onSubmit or onVlauesChange?

**Comment by vantezzen** [comment]
Hey, that functionality was only recently added with #103. Maybe @rumeshudash can provide some guidance here.

**Comment by tecoad** [comment]
Thanks for this @vantezzen! Did not noticed it was so recent. Just upgraded, thanks!

Btw, i am trying to reproduce a "check alias availability" example within onChange...
My first approach, was to use .refine() from zod:

```
.refine(
	async alias => {
		try {
			const { data: aliasAvailability } = await client.rpc(
				'affiliate_check_alias_availability',
				{
					alias_to_check: alias,
				}
			)
			return !aliasAvailability
		} catch (error) {
			return false
		}
	},
	{
		message: "Alias in use",
	}
),
``` 

But i noticed this "Error: Async refinement encountered during synchronous parse operation. Use .parseAsync instead."

This usecase has been tested before? if not.. (Plan B is validating with debounce on onValuesChange, but haven't figure out how to set error from there...
how would you build such a feature?

**Comment by rumeshudash** [comment]
> This usecase has been tested before? if not.. (Plan B is validating with debounce on onValuesChange, but haven't figure out how to set error from there... how would you build such a feature?

Hey @tecoad, maybe this PR #109 solves your issue.

**Comment by tecoad** [comment]
@rumeshudash how do you clear the error?

**Comment by rumeshudash** [comment]
> @rumeshudash how do you clear the error?

Exactly, here is better solution then this #112

**Comment by rumeshudash** [comment]
Now you have full access to form object of `react-hook-form`. #112
