### ISSUE TITLE
Lookup Field ?

### ISSUE THREAD

**Issue by leandrorazevedo** [vantezzen/autoform#11]
Would it be possible to create a select with data from an api? 
Something similar to a lookup field.

**Comment by vantezzen** [comment]
I don't know about lookup fields but you can look at https://github.com/vantezzen/auto-form/blob/main/src/examples/Api.tsx for an example on how to generate the form schema dynamically

**Comment by jedimonkey** [comment]
This doesn't support name/value pairs does it? I've been mucking around with your form (nice work btw!) and I have an idea on how to make it work, so will try to have a crack on this... time permitting 😅

**Comment by darkterminal** [comment]
I have been done with this and I will make a PR!
![image](https://github.com/vantezzen/auto-form/assets/32319439/29894b5d-612d-459d-bf05-858bdd793018)

The new `fieldType` is `options` 🎉
