### ISSUE TITLE
Label not added to date field

### ISSUE THREAD

**Issue by michaelbrusegard** [vantezzen/autoform#116]
When using zod with describe on a datefield the label is not added to the field. The error message works though

**Comment by michaelbrusegard** [comment]
A temporary fix is to define a custom date field and specify that in the field prop in the fieldconfig

**Comment by vantezzen** [comment]
Oh I see, date fields should not hide the label:

https://github.com/vantezzen/autoform/blob/6859fd6c3f5465d10109f6c4ab04cc022506d95c/packages/shadcn/src/components/ui/autoform/components/FieldWrapper.tsx#L5

Will fix this in the next release!

**Comment by michaelbrusegard** [comment]
I didnt see that part on my fieldwrapper, my mistake. Thanks for highlighting it! should be fixed now
