### ISSUE TITLE
zodProvider should accept ZodEffects

### ISSUE THREAD

**Issue by michaelbrusegard** [vantezzen/autoform#118]
I am sorry for bombarding you with issues, but I will forget them if I do not. The ZodProvider currently only supports the type ZodObject. But a zod validation can also be of the type ZodEffects when validating across fields. It works fine to use ZodEffects but the typescript type does not accept it. so it should be added that it could either be a ZodObject or ZodEffects

**Comment by vantezzen** [comment]
Oh you're right - seems like I accidentally switched the main schema type from `ZodObjectOrWrapped` to pure Zod objects only. WIll be fixed with the next release!
