### ISSUE TITLE
Validate `onTouched` instead of `onSubmit`

### ISSUE THREAD

**Issue by michaelbrusegard** [vantezzen/autoform#119]
How do I validate `onTouched`? This may be a limitation of the current version because it is not using react-hook-form but I am unsure

**Comment by vantezzen** [comment]
With autoform@2 you should be able to get access to the react-hook-form instance (https://autoform.vantezzen.io/docs/react/getting-started#using-onforminit-and-values) but I think the event handlers don't get copied to the form element.
You could override the form UI element (https://autoform.vantezzen.io/docs/react/customization#override-ui-components) but I'll look into adding a prop to give props to the form element

**Comment by michaelbrusegard** [comment]
Yea I have my own cust UI components it is just that I want different things for different forms. I think it would make sense if the AutoForm forwarded most of its props directly to the form element like className etc. Does V2 use react-hook-form?

**Comment by vantezzen** [comment]
Autoform@2.1.0 now adds support for a `formProps` prop that you can use to pass props (https://autoform.vantezzen.io/docs/react/customization#form-element-customization).
Yes, v2 is now fully migrated to using react-hook-form instead of manually keeping track of form state
