### ISSUE TITLE
Create Accordion section

### ISSUE THREAD

**Issue by nicolasdonato** [vantezzen/autoform#127]
Hello,

With the previous version of `auto-form`, we have embedded zod objects and when we displayed the root object, the form was displayed with accordion sections.

With the new version, the accordion sections were disapeared.

How can we have the same behavior like the previous version ?

Thank you in advance.

**Comment by vantezzen** [comment]
How subobjects are rendered can be customized in "/components/ui/autoform/components/ObjectWrapper.tsx" or by overriding the "ObjectWrapper" UI component in individual forms with the `uiComponents={{ ObjectWrapper: ... }}` prop.
Currently it just returns the field via the children, but you can wrap this in an Accordion section instead.
