### ISSUE TITLE
Update landing page example to use coerce?

### ISSUE THREAD

**Issue by byronwall** [vantezzen/autoform#131]
I spent longer than I want to admit before realizing that `coerce` is needed to get numbers to parse correctly.  It's mentioned in the docs, but the main example on the landing page doesn't use it.  Instead you get a validation error.

Docs: https://autoform.vantezzen.io/docs/schema/zod

I assume the goal is to demo a working example?  If so, you should add `coerce` so it works.

Default schema:

```
z.object({
  name: z.string(),
  age: z.number(),
  isHuman: z.boolean(),
})
```

<img width="363" alt="image" src="https://github.com/user-attachments/assets/dbbf846e-3bc1-42b8-830d-4a08c19e3a4b">

With coerce:

```
z.object({
  name: z.string(),
  age: z.coerce.number(),
  isHuman: z.boolean(),
})
```

<img width="356" alt="image" src="https://github.com/user-attachments/assets/a63ba881-aaaa-4e04-8739-c0d35cf7edaa">

**Comment by vantezzen** [comment]
Oh you're right, thank you for reporting - that demo was created earlier in development when I tried to manually patch converting to numbers. I just pushed a fix
