### ISSUE TITLE
useFormContext import bug

### ISSUE THREAD

**Issue by stan-dot** [vantezzen/autoform#138]
`../../node_modules/.pnpm/@autoform+react@2.1.0/node_modules/@autoform/react/dist/index.mjs
Attempted import error: 'useFormContext' is not exported from 'react-hook-form' (imported as 'useFormContext').`

though in theory it should exist alright (https://react-hook-form.com/docs/useformcontext)
with this code

```typescript
import { AutoForm } from "@autoform/mui";
import { ZodProvider } from "@autoform/zod";
import { z } from "zod";

const userSchema = z.object({
  name: z.string(),
  birthday: z.coerce.date(),
  email: z.string().email(),
});

const schemaProvider = new ZodProvider(userSchema);

export function MyForm() {
  return (
    <AutoForm
      schema={schemaProvider}
      onSubmit={(data) => {
        console.log(data);
      }}
      withSubmit
    />
  );
}
```

my environment: 

- pnpm: 9.14.4
- node: v22.11.0
- os: debian 12 (bookworm)

**Comment by vantezzen** [comment]
Is this related to https://github.com/vantezzen/autoform/issues/128? Please make sure to use AutoForm in a client component

**Comment by stan-dot** [comment]
ah right
