### ISSUE TITLE
Creating a name package ?

### ISSUE THREAD

**Issue by mickaelalvs** [vantezzen/autoform#19]
Have you thought about providing an npm package for auto-form? 😊 

Maybe not make all the components available, or maybe make it possible to override them to have custom ones?

**Comment by vantezzen** [comment]
I think I'd rather leave auto-form in project-space - working with shadcn/ui components from inside libraries goes a bit against the idea of the library and I'd want devs to be able to customize and extend the components freely, e.g. if they don't like the way a component is displayed by default.
However, once custom registries (https://twitter.com/shadcn/status/1672311339098988544) are implemented in the shadcn cli, I'll split up AutoForm into separate components on a custom registry so you can install and update via something like `npx shadcn-ui@latest add autoform autoform-select autoform-date`
