### ISSUE TITLE
Select field with combobox implementation

### ISSUE THREAD

**Issue by shatgupt** [vantezzen/autoform#21]
First of all, great work here! You (and shadcn) are making huge difference for React beginners like me to create prototypes.

It will be really cool to have a searchable select ([combobox](https://ui.shadcn.com/docs/components/combobox)) especially for API use-cases where large number of results can be returned.

**Comment by iamsadat** [comment]
Hey There 👋
Can I work on this issue?

**Comment by vantezzen** [comment]
Yes feel free!

**Comment by iamsadat** [comment]
I have raised a PR do let me know if there are any changes required
