### ISSUE TITLE
Ignore certain zod field while generating the form

### ISSUE THREAD

**Issue by ninnroot** [vantezzen/autoform#25]
Is there a feature to let you ignore certain fields in the zod schema while generating the form?

For example:
```ts
<AutoForm 
    formSchema={formSchema}
    ignoreFields={["foo", "bar"]}>

</AutoForm>
```

**Comment by vantezzen** [comment]
AutoForm probably won't support this as it can't validate the schema due to missing fields.
You can use zod's `omit` function to change the schema directly instead.
