### ISSUE TITLE
bug: nativeEnums don't pass validation (including demo)

### ISSUE THREAD

**Issue by pmioduszewski** [vantezzen/autoform#28]
Basically, nativeEnums are broken now; I see this issue also on the demo page:

<img width="637" alt="image" src="https://github.com/vantezzen/auto-form/assets/43101981/c30fe9e2-727a-4a25-b2d4-3ab89ec8b570">

**Comment by hyoban** [comment]
Key and value need to be exchanged where defined and used, because zod verifies value.

```ts
const Fruits = {
  Apple: "apple",
  Banana: "banana",
  Cantaloupe: 3,
} as const;

const FruitEnum = z.nativeEnum(Fruits);

FruitEnum.parse("apple"); // passes
FruitEnum.parse("banana"); // passes
FruitEnum.parse(3); // passes
FruitEnum.parse("Cantaloupe"); // fails
```

https://github.com/vantezzen/auto-form/blob/main/src/components/ui/auto-form.tsx#L453
