### ISSUE TITLE
License Addition

### ISSUE THREAD

**Issue by serinuntius** [vantezzen/autoform#29]
### Description

This repository currently doesn't have a license. Adding a license is essential to clearly define the terms under which the code can be used, modified, or distributed.

### Suggested Solution

1. Determine the most appropriate license for this project. Some popular options include MIT, GPL, and Apache 2.0.
2. Add the selected license file to the root of the repository.
3. Update the README to reference the license.

### Additional Context

A clear license can encourage contributions by providing clarity on code usage and distribution. Without a license, users and contributors might be hesitant to interact with the project due to legal ambiguities.

Please let me know your thoughts or if there's a specific license you have in mind for this project.

**Comment by vantezzen** [comment]
License is defined as MIT at https://github.com/vantezzen/auto-form#license but I'll add a complete LICENSE file

**Comment by serinuntius** [comment]
Thanks for the reply. I missed it, I will close it.
