### ISSUE TITLE
Props must be serializable for client components

### ISSUE THREAD

**Issue by thepeterkovacs** [vantezzen/autoform#3]
This issue occurs in the **date-picker** ui component at the **setDate** prop when using it in **Next.js 13.4**.

```tsx
"use client"
...
export function DatePicker({ date, setDate }: { date?: Date; setDate: (date?: Date) => void }) {
...
```

**setDate** can not be of type **(date?: Date) => void**

**Comment by vantezzen** [comment]
From what I can tell, it looks like serialization for the whole zod schema is problematic with server components. I tried using the [SuperJSON plugin](https://github.com/blitz-js/next-superjson-plugin) but that only throws other serialization errors.

For now, I would recommend using the AutoForm component inside a client component. If someone finds a way to enable using AutoForm in server components I'm happy to accept a PR!

**Comment by raphaelmsr** [comment]
Hey there! Would this help in anyway ? https://kitchen-sink.trpc.io/react-hook-form?file=feature%2Freact-hook-form%2Findex.tsx#content
Just found that looking for options in zod's repo issues! Would gladly help
