### ISSUE TITLE
[Bug] Deletion doesn't work properly in Array Support

### ISSUE THREAD

**Issue by LarsArtmann** [vantezzen/autoform#30]
## Just tried the Array Support on the [demo website](https://vantezzen.github.io/auto-form/).

<img width="651" alt="Screenshot 2023-09-17 at 17 26 08" src="https://github.com/vantezzen/auto-form/assets/23587853/e48622d8-9732-4a65-a14f-47c1e146d840">

## When I deleted the first entry this happened:
<img width="576" alt="Screenshot 2023-09-17 at 17 29 21" src="https://github.com/vantezzen/auto-form/assets/23587853/6b688bbd-e4eb-449a-8c48-ed166a407040">

### You can see the first entry is this there but the second one was 'delete'. If you look closely you can see it only removed it from the ui not the json underneath. After clicking the add button again it magically reappears. 
<img width="614" alt="Screenshot 2023-09-17 at 17 31 17" src="https://github.com/vantezzen/auto-form/assets/23587853/71ad5cdb-f8ce-47c6-ba58-985c7d6b57b7">

## After testing with 3 entries, it looks like the delete button always (no matter witch entry) deletes the last entry (from the ui only)

**Comment by teoboetti** [comment]
Searching on [react-hook-form](https://github.com/react-hook-form/react-hook-form), [this](https://github.com/react-hook-form/react-hook-form/issues/1571#issuecomment-690882455) should be the fix
