### ISSUE TITLE
required_error message never shows

### ISSUE THREAD

**Issue by johann-taberlet** [vantezzen/autoform#39]
First, thanks for this project.

I don't know if I'm doing something wrong but the required_error message is never shown for me. Native browser error does.
```ts
const formSchema = z.object({
        email: z.
            string({
                required_error: "Veuillez renseigner votre e-mail.",
            })
            .email({
                message: "E-mail incorrect.",
            })
    });
```

![iScreen Shoter - Google Chrome - 231016002710](https://github.com/vantezzen/auto-form/assets/9981334/a882ea2e-bf03-4306-9ae7-00aa6212494b)

Am I doing something wrong ?

Email format check error works as intended and display the red message.

**Comment by vantezzen** [comment]
This is expected behavior: The native errors validate before the zod validations are made. So if the native validation fails it will not get to zod - only if native validation passes.

If you want, you can remove the native validation code to only show zod errors.

**Comment by johann-taberlet** [comment]
Thanks, I just found the answer (which was actually in the question). 

Adding ```formNoValidate``` on the submit button indeed solved that issue.
