### ISSUE TITLE
React.forwardRef()

### ISSUE THREAD

**Issue by HighError** [vantezzen/autoform#4]
When I create a form that is in Dialog:
![image](https://github.com/vantezzen/auto-form/assets/46526245/dd91f67e-4697-4324-9e7f-09e82d64f770)
When I open Dialog, I get an error/warning in the console:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```
![image](https://github.com/vantezzen/auto-form/assets/46526245/ee6e0f7d-f757-4b78-8556-80955a255935)

Do I need to react to it, or can it be ignored?

**Comment by vantezzen** [comment]
Should be fixed via https://github.com/vantezzen/auto-form/commit/0b5edc5b12c4da8fc7ed6611c66fcce885acdf4b
