### ISSUE TITLE
Array support?

### ISSUE THREAD

**Issue by EliasGcf** [vantezzen/autoform#5]
Would be nice to support ZodArray type. React Hook Form has a `useFieldArray` hook to help add, remove, etc.

**Comment by vantezzen** [comment]
Good idea - do you have any specific use-cases in mind for this? Just so I can get an idea of how it should behave

**Comment by EliasGcf** [comment]
> Good idea - do you have any specific use-cases in mind for this? Just so I can get an idea of how it should behave

@vantezzen , my use-case is for an array of objects, but I think this feature should allow any registered shape (number, string, etc) and include buttons to add, remove, move up, and down (`useFieldArray` allow this)

Visually, something like this:

![image](https://github.com/vantezzen/auto-form/assets/50633599/0de22f30-441b-4b70-a237-6120bb954fd1)

**Comment by vantezzen** [comment]
Just added basic support for arrays, might look into improving the design and adding more advanced features like reordering in the future - otherwise PRs are welcome!

https://github.com/vantezzen/auto-form#arrays
