### ISSUE TITLE
Confirm password does not work

### ISSUE THREAD

**Issue by hkbertoson** [vantezzen/autoform#6]
````
const formSchema = z
	.object({
		password: z.string(),
		confirm: z.string(),
	})
	.refine((data) => data.password === data.confirm, {
		message: 'Passwords must match.',
		path: ['confirm'],
	});
````

````
			<AutoForm
				formSchema={formSchema}
				fieldConfig={{
					password: {
						inputProps: {
							type: 'password',
							placeholder: '••••••••',
						},
					},
					confirm: {
						inputProps: {
							type: 'password',
							placeholder: '••••••••',
						},
					},
				}}
			>
````

Throws this error

<img width="956" alt="image" src="https://github.com/vantezzen/auto-form/assets/44106297/eb3c4d6b-d468-46bc-b5b5-ce63eab79037">

**Comment by vantezzen** [comment]
AutoForm didn't support top-level refinements and excepted the outer zod object to not be wrapped.
I now updated it to support that. 

The TypeScript type is still slightly wrong as it doesn't allow multiple levels of ZodEffects but the code does. TypeScript doesn't seem to like circular type definitions so I'll have to look into how to circumvent this.
