### ISSUE TITLE
feature request: be able to reorder fields

### ISSUE THREAD

**Issue by capaj** [vantezzen/autoform#63]
I am generating schemas from drizzle tables so I don't control order of fields. Would be awesome to be able to reorder in fieldconfig

**Comment by feliche93** [comment]
Not the full answer, but I am currently using `pick` to get around this:

```
export const SNewWebsiteForm = createInsertSchema(xx).pick({
  firstField: true,
  secondField: True,
})
```

This will orderi t for me, at least. Not perfect, but most often I need to kick out some fields anyways.

**Comment by AdhikaryGautam** [comment]
There's now support of reordering the fields through fieldConfig.
