### ISSUE TITLE
onChange not getting fired on any field

### ISSUE THREAD

**Issue by imprakharshukla** [vantezzen/autoform#66]
Hey! Awesome library, saves a bunch of time.

However, I am facing this issue while I am trying to display the photos selected by the user through a file input.

```ts
 fieldConfig={{
                images: {
                    description: "Upload images",
                    fieldType: "file",
                    inputProps: {
                        multiple: true,
                        accept: "image/*",
                        onChange: (e) => {
                            console.log({ e })
                        },
                    }
                },
```

onChange is not getting fired on this or any other field. How can I fix this?

**Comment by cipriancaba** [comment]
Have you tried to use `onValuesChange` on the `AutoForm` component directly?

**Comment by imprakharshukla** [comment]
That's what I have resorted to use for now.
