### ISSUE TITLE
Dependencies for nested fields

### ISSUE THREAD

**Issue by imprakharshukla** [vantezzen/autoform#69]
Hey! I am trying to implement a rather complex form and would like to apply dependencies on nested fields. Here's a sample schema:

```ts
 inventory: z
    .array(
      z.object({
        size: z.enum([
          "XXS",
          "XS",
          "S",
          "M",
          "L",
          "XL",
          "XXL",
          "XXXL",
          "Free Size",
          "One Size",
          "Custom",
        ]),
        customSize: z.string().optional(),
        measurements: z.object({
          bust: z.number().optional(),
          waist: z.number().optional(),
        }),
        variant: z.array(
          z.object({
            name: z.string(),
            quantity: z.number(),
            price: z.number(),
          }),
        ),
      }),
    )
```

What i am trying to do is show and hide the custom size field depending upon the current value of the size select. The docs do not mention how to name the dependencies when dealing with nested fields.

Grateful for any help.

**Comment by vantezzen** [comment]
I don't know if the code correctly handles nesting but you can try using dot notation like "inventory.size" - otherwise I'd be happy to accept PRs to add this
