### ISSUE TITLE
question: Is there a way to render into grid?

### ISSUE THREAD

**Issue by capaj** [vantezzen/autoform#70]
I have tried just slapping className='grid grid-cols-2 gap-4' onto `Autoform` but no luck.
Is there a way to achieve grid layout?

**Comment by sheldonpang** [comment]
I'd achieve in this way, make accordion a grid layout with cols size, then set child fields "col-span-x"

<img width="567" alt="image" src="https://github.com/vantezzen/auto-form/assets/8623419/8e1bf023-4713-4119-bb49-5800fd25569b">
<img width="670" alt="image" src="https://github.com/vantezzen/auto-form/assets/8623419/f0cbcb4a-2a16-4910-aca8-d5481b225b97">
