### ISSUE TITLE
add Multiple Selector from Shadcn-expansion

### ISSUE THREAD

**Issue by DrummyFloyd** [vantezzen/autoform#83]
Would be great to add this kind of component in autoform 

https://shadcnui-expansions.typeart.cc/docs/multiple-selector

**Comment by a0m0rajab** [comment]
There is a conversation about it here: https://github.com/vantezzen/auto-form/issues/35

**Comment by vantezzen** [comment]
This would require the component to be installed for AutoForm to be installed - if you want to use it, you should be able to easily add it locally like this: https://github.com/vantezzen/auto-form#adding-new-components
