### ISSUE TITLE
useEffect has missing dependencies Typescript error!

### ISSUE THREAD

**Issue by kayoroxa** [vantezzen/autoform#85]
![image](https://github.com/vantezzen/auto-form/assets/54248474/77a7219b-b2c3-4d92-bce6-3bc7d17f1091)

![image](https://github.com/vantezzen/auto-form/assets/54248474/bf469e0f-cbbf-4493-a82c-6d3b8ac1b4e2)

React Hook React.useEffect has missing dependencies: 'formSchema', 'onParsedValuesChange', 'onValuesChangeProp', and 'values'. Either include them or remove the dependency array. If 'onValuesChangeProp' changes too often, find the parent component that defines it and wrap that definition in useCallback.

File: auto-form/index.tsx

And when trying to fix this error, this other thing happens: use effect Maximum update depth exceeded.

**Comment by kayoroxa** [comment]
I temporarily solved it by putting: 

// eslint-disable-next-line react-hooks/exhaustive-deps

![image](https://github.com/vantezzen/auto-form/assets/54248474/cac8729d-de0c-451e-8cc6-b1206144c948)

**Comment by cwdaniel** [comment]
This happens when you hold down a character to long in a form and is happening specifically because the values aren't being debounced in the useEffect. You can create a debounce of the valueString and that will stop this issue from blowing up your app. 

Heres a simple debounce hook. 
```typescript
import { useEffect, useState } from 'react';

const useDebounce = <T>(value: T, delay: number): T => {
    const [debouncedValue, setDebouncedValue] = useState<T>(value);

    useEffect(() => {
        const timer = setTimeout(() => {
            setDebouncedValue(value);
        }, delay);

        return () => {
            clearTimeout(timer);
        };
    }, [value, delay]);

    return debouncedValue;
};

export default useDebounce;
```
with this you can replace the valueString at line 86 of index.tsx in autoform\index.tsx and update the useEffect.

```typescript
  const valuesString = JSON.stringify(values);
  //debounce the value string
  const debouncedValuesString = useDebounce(valuesString, 500);
  
  React.useEffect(() => {
    onValuesChangeProp?.(values);
    const parsedValues = formSchema.safeParse(values);
    if (parsedValues.success) {
      onParsedValuesChange?.(parsedValues.data);
    }
  }, [debouncedValuesString]);
  ```
