### ISSUE TITLE
enums and select is being reset when setting the values externally

### ISSUE THREAD

**Issue by a0m0rajab** [vantezzen/autoform#92]
We tried to use values externally to set some values of the form by using this method: https://github.com/vantezzen/auto-form?tab=readme-ov-file#controlled-form

when the form is generated the enum values is being reset and not showing.

**Comment by a0m0rajab** [comment]
@vantezzen  was this implemented?

**Comment by vantezzen** [comment]
The new AutoForm has been rewritten and it looks like this is fixed: https://codesandbox.io/p/sandbox/autoform-mui-demo-3pjwvr

**Comment by a0m0rajab** [comment]
Thank you for the answer
