### ISSUE TITLE
[bug] date picker missing

### ISSUE THREAD

**Issue by moltco** [vantezzen/autoform#96]
I am new to shadcn and auto-form, so followed installation instrucitons and then found that auto-forms wont compile as it is missing DatePicker component in import at components\ui\auto-form\fields\date.tsx (```import { DatePicker } from "@/components/ui/date-picker";```)

At first I thought shadcn-ui had a bug as I could not add date-picker component and raised an issua around this `https://github.com/shadcn-ui/ui/issues/4786` However, reading shadcn instrucitons for date-picker it appears this component is not installed by/from shadcn but rather needs to be created separately.

I see in auto-form there is date-picker.tsx but when I follow installation instructions, this component is not installed - I believe there may be a bug in the installation script/instructions?

**Comment by jayarjo** [comment]
Same here.

**Comment by vantezzen** [comment]
Thank you for reporting this. I've updated the registry file so it should now install the date picker and zod if it's not installed yet
